import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useParams, useLocation } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { Order } from "@shared/schema";
import { format } from "date-fns";
import { Printer } from "lucide-react";

export default function ChallanView() {
  const { id } = useParams();
  const [, setLocation] = useLocation();
  const { data: order } = useQuery<Order>({ queryKey: [`/api/orders/${id}`] });

  if (!order) return <div className="p-8 text-center">Loading challan...</div>;

  return (
    <div className="p-6 max-w-4xl mx-auto space-y-8">
      <div className="flex justify-between items-center no-print">
        <Button variant="outline" onClick={() => setLocation(`/orders/${id}`)}>Back to Details</Button>
        <Button onClick={() => window.print()}><Printer className="mr-2 h-4 w-4" /> Print Challan</Button>
      </div>

      <Card className="print:border-0 print:shadow-none">
        <CardContent className="p-12 space-y-8">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-4xl font-bold text-primary">CHALLAN</h1>
              <p className="text-muted-foreground">WMS Pro Logistics</p>
            </div>
            <div className="text-right">
              <p className="font-bold">Order #: {order.orderId}</p>
              <p className="text-sm">Date: {format(new Date(), "MMM dd, yyyy")}</p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-12 border-y py-8">
            <div>
              <h3 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-2">From:</h3>
              <p className="font-bold">WMS Pro Main Warehouse</p>
              <p className="text-sm">Industrial Zone 1, Suite 100</p>
              <p className="text-sm">Tech City, TC 12345</p>
            </div>
            <div>
              <h3 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-2">To:</h3>
              <p className="font-bold">{order.customer}</p>
              <p className="text-sm">Shipping Address Provided via System</p>
              <p className="text-sm">Contact: (555) 000-0000</p>
            </div>
          </div>

          <table className="w-full">
            <thead>
              <tr className="border-b text-left">
                <th className="py-4">Item Description</th>
                <th className="py-4 text-right">Quantity</th>
                <th className="py-4 text-right">Weight</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b">
                <td className="py-4">Warehouse Items (Consolidated)</td>
                <td className="py-4 text-right">{order.totalQuantity}</td>
                <td className="py-4 text-right">--</td>
              </tr>
            </tbody>
          </table>

          <div className="pt-12 flex justify-between">
            <div className="space-y-4">
              <p className="text-xs text-muted-foreground italic">Authorized Signature</p>
              <div className="w-48 border-b"></div>
            </div>
            <div className="text-right space-y-2">
              <p className="text-sm font-medium">Total Quantity: {order.totalQuantity}</p>
              <p className="text-xs text-muted-foreground">Generated by WMS Pro System</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
